#!/bin/bash
echo "=== Verificación de Configuración DVirtualHome ==="
echo ""
echo "1. Theos instalado:"
[ -d "$THEOS" ] && echo "   ✅ $THEOS" || echo "   ❌ No encontrado"
echo ""
echo "2. SDK disponible:"
ls -d $THEOS/sdks/iPhoneOS*.sdk 2>/dev/null | head -1 && echo "   ✅ SDK encontrado" || echo "   ❌ No hay SDK"
echo ""
echo "3. Toolchain:"
$THEOS/toolchain/linux/iphone/bin/arm64-apple-darwin14-clang --version 2>/dev/null | head -1 && echo "   ✅ Toolchain funcional" || echo "   ❌ Toolchain no funcional"
echo ""
echo "4. Prefix.pch:"
[ -f "$THEOS/Prefix.pch" ] && echo "   ✅ Existe" || echo "   ❌ No existe"
echo ""
echo "5. Configuración Makefile:"
grep -E "TARGET|THEOS_DISABLE" Makefile 2>/dev/null && echo "   ✅ Configurado" || echo "   ❌ No configurado"
echo ""
echo "=== Estado: Listo para compilar con SDK compatible ==="
